apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.fullname" . }}-secrets
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.auth.rootPassword | b64enc | trimSuffix "\n" }}
  mysql-password: {{ .Values.auth.password | b64enc | trimSuffix "\n" }}

