apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "batch-server.fullname" . }}-envoy-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "batch-server.name" . }}
    chart: {{ template "batch-server.chart" . }}
    release: {{ template "batch-server.fullname" . }}
    heritage: {{ .Release.Service }}
data:
  config.yaml: |-
    admin:
      access_log:
        name: envoy.access_loggers.file
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
          path: /dev/stdout
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8001
    static_resources:
      clusters:
        - name: batch
          type: strict_dns
          lb_policy: round_robin
          connect_timeout: 5s
          dns_lookup_family: V4_ONLY
          load_assignment:
            cluster_name: batch
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: localhost
                          port_value: 9090
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
              common_tls_context:
                alpn_protocols:
                  - h2
                tls_certificates:
                  - certificate_chain:
                      filename: /usr/local/certs/service/tls.crt
                    private_key:
                      filename: /usr/local/certs/service/tls.key
          typed_extension_protocol_options:
            envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
              '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
              explicit_http_config:
                http2_protocol_options: {}
          health_checks:
            - grpc_health_check: {}
              healthy_threshold: 1
              interval: 10s
              interval_jitter: 1s
              no_traffic_interval: 2s
              timeout: 1s
              unhealthy_threshold: 2
          ignore_health_on_host_removal: true

        - name: backend
          type: strict_dns
          lb_policy: round_robin
          connect_timeout: 5s
          dns_lookup_family: V4_ONLY
          load_assignment:
            cluster_name: backend
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: backend.{{ .Values.namespace }}.svc.cluster.local
                          port_value: 9000
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
              common_tls_context:
                alpn_protocols:
                  - h2
                tls_certificates:
                  - certificate_chain:
                      filename: /usr/local/certs/service/tls.crt
                    private_key:
                      filename: /usr/local/certs/service/tls.key
          typed_extension_protocol_options:
            envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
              '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
              explicit_http_config:
                http2_protocol_options: {}
          ignore_health_on_host_removal: true

        - name: experiment-calculator
          dns_lookup_family: V4_ONLY
          connect_timeout: 5s
          ignore_health_on_host_removal: true
          type: strict_dns
          lb_policy: round_robin
          typed_extension_protocol_options:
            envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
              '@type': type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
              explicit_http_config:
                http2_protocol_options: {}
          load_assignment:
            cluster_name: experiment-calculator
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: experiment-calculator.{{ .Values.namespace }}.svc.cluster.local
                          port_value: 9000
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
              common_tls_context:
                alpn_protocols: ["h2"]
                tls_certificates:
                  - certificate_chain:
                      filename: /usr/local/certs/service/tls.crt
                    private_key:
                      filename: /usr/local/certs/service/tls.key

      listeners:
        - name: ingress
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 9000
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    access_log:
                      name: envoy.access_loggers.file
                      typed_config:
                        '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                        path: /dev/stdout
                    codec_type: auto
                    http_filters:
                      - name: envoy.filters.http.health_check
                        typed_config:
                          '@type': type.googleapis.com/envoy.extensions.filters.http.health_check.v3.HealthCheck
                          cluster_min_healthy_percentages:
                            batch:
                              value: 25
                          headers:
                            - name: :path
                              string_match:
                                exact: /health
                          pass_through_mode: false
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                    route_config:
                      virtual_hosts:
                        - name: ingress_services
                          domains:
                            - '*'
                          routes:
                            - match:
                                headers:
                                  - name: content-type
                                    string_match:
                                      exact: application/grpc
                                prefix: /
                              route:
                                cluster: batch
                                retry_policy:
                                  num_retries: 3
                                  retry_on: 5xx
                                timeout: 1800s
                    stat_prefix: ingress_http
                    stream_idle_timeout: 300s
              transport_socket:
                name: envoy.transport_sockets.tls
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
                  common_tls_context:
                    alpn_protocols:
                      - h2
                    tls_certificates:
                      - certificate_chain:
                          filename: /usr/local/certs/service/tls.crt
                        private_key:
                          filename: /usr/local/certs/service/tls.key
                  require_client_certificate: true

        - name: egress
          address:
            socket_address:
              address: 127.0.0.1
              port_value: 9001
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    access_log:
                      name: envoy.access_loggers.file
                      typed_config:
                        '@type': type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                        path: /dev/stdout
                    codec_type: auto
                    http_filters:
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                    route_config:
                      virtual_hosts:
                        - name: egress_services
                          domains:
                            - '*'
                          routes:
                            - match:
                                headers:
                                  - name: content-type
                                    string_match:
                                      exact: application/grpc
                                prefix: /bucketeer.autoops.AutoOpsService
                              route:
                                cluster: backend
                                retry_policy:
                                  num_retries: 3
                                  retry_on: 5xx
                                timeout: 15s
                            - match:
                                headers:
                                  - name: content-type
                                    string_match:
                                      exact: application/grpc
                                prefix: /bucketeer.notification.NotificationService
                              route:
                                cluster: backend
                                retry_policy:
                                  num_retries: 3
                                  retry_on: 5xx
                                timeout: 15s
                            - match:
                                headers:
                                  - name: content-type
                                    string_match:
                                      exact: application/grpc
                                prefix: /bucketeer.environment.EnvironmentService
                              route:
                                cluster: backend
                                retry_policy:
                                  num_retries: 3
                                  retry_on: 5xx
                                timeout: 60s
                            - match:
                                headers:
                                  - name: content-type
                                    string_match:
                                      exact: application/grpc
                                prefix: /bucketeer.experiment.ExperimentService
                              route:
                                cluster: backend
                                retry_policy:
                                  num_retries: 3
                                  retry_on: 5xx
                                timeout: 60s
                            - match:
                                headers:
                                  - name: content-type
                                    string_match:
                                      exact: application/grpc
                                prefix: /bucketeer.eventcounter.EventCounterService
                              route:
                                cluster: backend
                                retry_policy:
                                  num_retries: 3
                                  retry_on: 5xx
                                timeout: 1800s
                            - match:
                                headers:
                                  - name: content-type
                                    string_match:
                                      exact: application/grpc
                                prefix: /bucketeer.experimentcalculator.ExperimentCalculatorService
                              route:
                                cluster: experiment-calculator
                                timeout: 1800s
                                retry_policy:
                                  retry_on: 5xx
                                  num_retries: 3
                            - match:
                                headers:
                                  - name: content-type
                                    string_match:
                                      exact: application/grpc
                                prefix: /bucketeer.feature.FeatureService
                              route:
                                cluster: backend
                                retry_policy:
                                  num_retries: 3
                                  retry_on: 5xx
                                timeout: 15s
                    stat_prefix: egress_http
                    stream_idle_timeout: 300s
              transport_socket:
                name: envoy.transport_sockets.tls
                typed_config:
                  '@type': type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
                  common_tls_context:
                    alpn_protocols:
                      - h2
                    tls_certificates:
                      - certificate_chain:
                          filename: /usr/local/certs/service/tls.crt
                        private_key:
                          filename: /usr/local/certs/service/tls.key
                  require_client_certificate: true
