global:
  image:
    tag: test
    imagePullSecrets:

env:
  logLevel: debug
  profile: false
  gcpEnabled: false
  pubsubEmulatorHost: localenv-pubsub.default.svc.cluster.local:8089
  # egress services
  featureService: localhost:9001
  autoOpsService: localhost:9001
  # rpc
  port: 9090
  metricsPort: 9002
  # pubsub
  project: bucketeer-test
  topic: evaluation
  subscription: evaluation-ops-sub
  pullerNumGoroutines: 5
  pullerMaxOutstandingMessages: "1000"
  pullerMaxOutstandingBytes: "1000000000"
  # redis
  redis:
    serverName: event-persister
    addr: localenv-redis-headless.default.svc.cluster.local:6379
    poolMaxIdle: 25
    poolMaxActive: 25
  # batch options
  maxMps: "1000"
  numWorkers: 5
  flushSize: 100
  flushInterval: 2s
  flushTimeout: 30s

tls:
  service:
    secret: bucketeer-service-cert

serviceToken:
  secret:
  token: 
