apiVersion: v1
kind: Service
metadata:
  name: {{ include "pubsub.fullname" . }}
  labels:
    {{- include "pubsub.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.image.containerPort }}
      targetPort: {{ .Values.image.containerPort }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "pubsub.selectorLabels" . | nindent 4 }}
