apiVersion: v2
name: localenv
version: 1.1.0
description: This Chart deploys local environment.
dependencies:
- name: redis
  version: "1.1.0"
  repository: "file://./dependencies/redis"
- name: mysql
  version: "1.1.0"
  repository: "file://./dependencies/mysql"
- name: pubsub
  version: "1.1.0"
  repository: "file://./dependencies/pubsub"
- name: bq
  version: "1.1.0"
  repository: "file://./dependencies/bq"
- name: vault
  version: "0.23.0"
  repository: "https://helm.releases.hashicorp.com"