version: 0.1.0

vault:
  server:
    dev:
      enabled: true
      devRootToken: "root"

redis:
  architecture: "standalone"
  image:
    registry: docker.io
    repository: redis
    tag: 8.4.0
  auth: 
    enabled: false
  volumePermissions:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/os-shell
      tag: latest

nginx:
  controller:
    service:
      loadBalancerIP: "192.168.49.2"
      externalIPs:
      - 127.0.0.1
      - 192.168.49.2

mysql:
  image:
    registry: docker.io
    repository: bitnamilegacy/mysql
    tag: "8.4.5-debian-12-r0"
  initdbScriptsConfigMap: mysql-initdb
  volumePermissions:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/os-shell
      tag: latest
  auth:
    username: "bucketeer"
    password: "bucketeer"
    database: "bucketeer"
    rootPassword: "YnVja2V0ZWVy"
  primary:
    service:
      type: NodePort
      nodePorts:
        postgresql: 32000

postgresql:
  image:
    registry: docker.io
    repository: postgres
    tag: "18"
  auth:
    username: "bucketeer"
    password: "bucketeer"
    database: "bucketeer"
    postgresPassword: "bucketeer"
  volumePermissions:
    enabled: true
  primary:
    podSecurityContext:
      enabled: true
      fsGroup: 1001
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsNonRoot: true
      readOnlyRootFilesystem: false
    service:
      type: NodePort
      nodePorts:
        postgresql: 32100

bq:
  project: bucketeer-test
  service:
    type: NodePort
    httpNodePort: 31000
  image:
    repository: ghcr.io/bucketeer-io/bigquery-emulator
    
pubsub: 
  image: 
    tag: "449.0.0"