version: 0.1.0

vault:
  server:
    dev:
      enabled: true
      devRootToken: "root"

redis:
  architecture: "standalone"
  image:
    registry: docker.io
    repository: redis
    tag: 8.4.0
  auth: 
    enabled: false
  volumePermissions:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/os-shell
      tag: latest

nginx:
  controller:
    service:
      loadBalancerIP: "192.168.49.2"
      externalIPs:
      - 127.0.0.1
      - 192.168.49.2

mysql:
  image:
    registry: docker.io
    repository: mysql
    tag: "9"
  initdbScriptsConfigMap: mysql-initdb
  #diagnosticMode:
  #  enabled: true
  volumePermissions:
    enabled: true
    image:
      registry: docker.io
      repository: bitnami/os-shell
      tag: latest
  auth:
    database: "bucketeer"
    username: "bucketeer"
    password: "bucketeer"
  primary:
    service:
      type: NodePort
      nodePorts:
        mysql: 32000

bq:
  project: bucketeer-test
  service:
    type: NodePort
    httpNodePort: 31000
  image:
    repository: ghcr.io/bucketeer-io/bigquery-emulator
    
pubsub: 
  image: 
    tag: "449.0.0"