version: 0.1.0

vault:
  server:
    dev:
      enabled: true
      devRootToken: "root"

redis-cluster:
  # Configure the cluster
  cluster:
    nodes: 3  # Minimum required nodes for Redis Cluster (3 masters + 3 replicas)
    replicas: 0  # Number of replicas for each master

redis:
  architecture: "standalone"
  auth:
    enabled: false

nginx:
  controller:
    service:
      loadBalancerIP: "192.168.49.2"
      externalIPs:
      - 127.0.0.1
      - 192.168.49.2

mysql:
  image:
    tag: "8.0"
  initdbScriptsConfigMap: mysql-initdb
  #diagnosticMode:
  #  enabled: true
  volumePermissions:
    enabled: true
  auth:
    database: "bucketeer"
    username: "bucketeer"
    password: "bucketeer"
  primary:
   service:
     type: NodePort
     nodePorts:
       mysql: 32000

bq:
  project: bucketeer-test
  service:
    type: NodePort
    httpNodePort: 31000
  image:
    repository: ghcr.io/bucketeer-io/bigquery-emulator

pubsub:
  image:
    tag: "449.0.0"