apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "web.fullname" . }}-email-config
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "web.name" . }}
    chart: {{ template "web.chart" . }}
    release: {{ template "web.fullname" . }}
    heritage: {{ .Release.Service }}
data:
  email-config.json: |-
    {{ toJson .Values.email }}
