apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "api.name" . }}
    chart: {{ template "api.chart" . }}
    release: {{ template "api.fullname" . }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- if .Values.env.gcpEnabled }}
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.staticIPName }}
    {{- else }}
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    {{- end }}
spec:
  tls:
{{ toYaml .Values.tls.bucketeerJP.secrets | indent 4 }}
  rules:
{{ toYaml .Values.ingress.rules | indent 4 }}
