apiVersion: v1
kind: Secret
metadata:
  # Generates a name based on the chart release (e.g., postgres-secret)
  name: {{ include "postgres.fullname" . }}-secret
  labels:
  {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
data:
  # The password must be base64 encoded for Kubernetes Secrets
  postgres-password: {{ .Values.auth.password | b64enc | quote }}