type: mysql
batchSize: 1000
timezone: "UTC"
mysql:
  useMainConnection: true
  host: ""
  port: 3306
  user: ""
  password: ""
  database: ""
postgres:
  host: "postgres"
  port: 5432
  user: "bucketeer"
  password: "bucketeer"
  database: "bucketeer"
bigquery:
  project: ""
  dataset: ""
  location: "" 