{{- if and (eq (include "subscriber.shouldDeploy" .) "true") .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "subscriber.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ template "subscriber.name" . }}
{{ end }}
