apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "event-counter.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "event-counter.name" . }}
    chart: {{ template "event-counter.chart" . }}
    release: {{ template "event-counter.fullname" . }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "event-counter.name" . }}
      release: {{ template "event-counter.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "event-counter.name" . }}
        release: {{ template "event-counter.fullname" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/envoy-configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.global.image.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      volumes:
        - name: envoy-config
          configMap:
            name: {{ template "event-counter.fullname" . }}-envoy-config
        - name: service-cert-secret
          secret:
            secretName: {{ template "service-cert-secret" . }}
        - name: oauth-key-secret
          secret:
            secretName: {{ template "oauth-key-secret" . }}
        - name: service-token-secret
          secret:
            secretName: {{ template "service-token-secret" . }}
      serviceAccountName: {{ template "event-counter.name" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["server"]
          env:
            - name: BUCKETEER_EVENT_COUNTER_PROJECT
              value: "{{ .Values.env.project }}"
            - name: BUCKETEER_EVENT_COUNTER_EXPERIMENT_SERVICE
              value: "{{ .Values.env.experimentService }}"
            - name: BUCKETEER_EVENT_COUNTER_FEATURE_SERVICE
              value: "{{ .Values.env.featureService }}"
            - name: BUCKETEER_EVENT_COUNTER_ACCOUNT_SERVICE
              value: "{{ .Values.env.accountService }}"
            {{ if .Values.env.druidPassword }}
            - name: BUCKETEER_EVENT_COUNTER_DRUID_URL
              value: "{{ .Values.env.druidUrl }}"
            - name: BUCKETEER_EVENT_COUNTER_DRUID_DATASOURCE_PREFIX
              value: "{{ .Values.env.druidDatasourcePrefix }}"
            - name: BUCKETEER_EVENT_COUNTER_DRUID_USERNAME
              value: "{{ .Values.env.druidUsername }}"
            - name: BUCKETEER_EVENT_COUNTER_DRUID_PASSWORD
              value: "{{ .Values.env.druidPassword }}"
            {{ end }}
            - name: BUCKETEER_EVENT_COUNTER_BIGQUERY_DATA_SET
              value: "{{ .Values.env.bigQueryDataSet }}"
            - name: BUCKETEER_EVENT_COUNTER_BIGQUERY_DATA_LOCATION
              value: "{{ .Values.env.bigQueryDataLocation }}"
            - name: BUCKETEER_EVENT_COUNTER_MYSQL_USER
              value: "{{ .Values.env.mysqlUser }}"
            - name: BUCKETEER_EVENT_COUNTER_MYSQL_PASS
              value: "{{ .Values.env.mysqlPass }}"
            - name: BUCKETEER_EVENT_COUNTER_MYSQL_HOST
              value: "{{ .Values.env.mysqlHost }}"
            - name: BUCKETEER_EVENT_COUNTER_MYSQL_PORT
              value: "{{ .Values.env.mysqlPort }}"
            - name: BUCKETEER_EVENT_COUNTER_MYSQL_DB_NAME
              value: "{{ .Values.env.mysqlDbName }}"
            - name: BUCKETEER_EVENT_COUNTER_PORT
              value: "{{ .Values.env.port }}"
            - name: BUCKETEER_EVENT_COUNTER_METRICS_PORT
              value: "{{ .Values.env.metricsPort }}"
            - name: BUCKETEER_EVENT_COUNTER_SERVICE_TOKEN
              value: /usr/local/service-token/token
            - name: BUCKETEER_EVENT_COUNTER_OAUTH_CLIENT_ID
              value: "{{ .Values.oauth.clientId }}"
            - name: BUCKETEER_EVENT_COUNTER_OAUTH_ISSUER
              value: "{{ .Values.oauth.issuer }}"
            - name: BUCKETEER_EVENT_COUNTER_OAUTH_KEY
              value: /usr/local/oauth-key/public.pem
            - name: BUCKETEER_EVENT_COUNTER_CERT
              value: /usr/local/certs/service/tls.crt
            - name: BUCKETEER_EVENT_COUNTER_KEY
              value: /usr/local/certs/service/tls.key
            - name: BUCKETEER_EVENT_COUNTER_REDIS_SERVER_NAME
              value: "{{ .Values.env.redis.serverName }}"
            - name: BUCKETEER_EVENT_COUNTER_REDIS_ADDR
              value: "{{ .Values.env.redis.addr }}"
            - name: BUCKETEER_EVENT_COUNTER_REDIS_POOL_MAX_IDLE
              value: "{{ .Values.env.redis.poolMaxIdle }}"
            - name: BUCKETEER_EVENT_COUNTER_REDIS_POOL_MAX_ACTIVE
              value: "{{ .Values.env.redis.poolMaxActive }}"
          volumeMounts:
            - name: service-cert-secret
              mountPath: /usr/local/certs/service
              readOnly: true
            - name: service-token-secret
              mountPath: /usr/local/service-token
              readOnly: true
            - name: oauth-key-secret
              mountPath: /usr/local/oauth-key
              readOnly: true
          ports:
            - name: service
              containerPort: {{ .Values.env.port }}
            - name: metrics
              containerPort: {{ .Values.env.metricsPort }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.health.initialDelaySeconds }}
            periodSeconds: {{ .Values.health.periodSeconds }}
            failureThreshold: {{ .Values.health.failureThreshold }}
            httpGet:
              path: /health
              port: service
              scheme: HTTPS
          readinessProbe:
            initialDelaySeconds: {{ .Values.health.initialDelaySeconds }}
            httpGet:
              path: /health
              port: service
              scheme: HTTPS
          resources:
{{ toYaml .Values.resources | indent 12 }}
        - name: envoy
          image: "{{ .Values.envoy.image.repository }}:{{ .Values.envoy.image.tag }}"
          imagePullPolicy: {{ .Values.envoy.image.pullPolicy }}
          lifecycle:
            preStop:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "while [ $(netstat -plunt | grep tcp | grep -v envoy | wc -l) -ne 0 ]; do sleep 1; done;"
          command: ["envoy"]
          args:
            - "-c"
            - "/usr/local/conf/config.yaml"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: envoy-config
              mountPath: /usr/local/conf/
              readOnly: true
            - name: service-cert-secret
              mountPath: /usr/local/certs/service
              readOnly: true
          ports:
            - name: envoy
              containerPort: {{ .Values.envoy.port }}
            - name: admin
              containerPort: {{ .Values.envoy.adminPort }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.health.initialDelaySeconds }}
            periodSeconds: {{ .Values.health.periodSeconds }}
            failureThreshold: {{ .Values.health.failureThreshold }}
            httpGet:
              path: /health
              port: envoy
              scheme: HTTPS
          readinessProbe:
            initialDelaySeconds: {{ .Values.health.initialDelaySeconds }}
            httpGet:
              path: /health
              port: envoy
              scheme: HTTPS
          resources:
{{ toYaml .Values.envoy.resources | indent 12 }}
  strategy:
    type: RollingUpdate
