name: cla
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == '/cla sign') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@a895a435fcce79ecf28fbce61a4ef0f0dabc9853 # v2.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_PAT }}
        with:
          remote-organization-name: bucketeer-io
          remote-repository-name: bucketeer-cla
          path-to-signatures: "cla/signatures.json"
          custom-notsigned-prcomment: "Welcome!\nThanks for your contribution. It looks like this is your first PR to this repository ðŸŽ‰. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA). Please read the [CLA](https://github.com/bucketeer-io/bucketeer/blob/main/CLA.md) and leave a below comment on this pull request to sign the CLA."
          custom-pr-sign-comment: "/cla sign"
          custom-allsigned-prcomment: "All Contributors have signed the CLA."
          lock-pullrequest-aftermerge: false
          branch: "main"
          allowlist: github-actions,renovate[bot],dependabot[bot]
