# This workflow will update the CHANGELOG page in the `bucketeer-io/bucketeer-docs` repository when a tag is created
name: update-changelog-docs-page

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      RELEASE_TAG: ${{ steps.release_tag.outputs.value }}
      COMMIT_URL: ${{ steps.commit_url.outputs.value }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - name: Store the tag value
        id: release_tag
        run: echo "value=$(git describe --tags --always --abbrev=0)" >> $GITHUB_OUTPUT
      - name: Store the first line of commit message
        id: commit_url
        run: echo "value=$(echo '${{ github.event.head_commit.url }}' | head -n 1)" >> $GITHUB_OUTPUT

  update_changelog_doc_page:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Workflow Dispatch
        uses: benc-uk/workflow-dispatch@e2e5e9a103e331dad343f381a29e654aea3cf8fc # v1.2.4
        env:
          DOC_REPO: bucketeer-io/bucketeer-docs
          DOC_FILENAME: core.mdx
          DOC_FILEPATH: docs/changelog
          DOC_TITLE: Core
          DOC_SLUG: /changelog/core
          CHANGELOG_URL: https://raw.githubusercontent.com/bucketeer-io/bucketeer/main/CHANGELOG.md
          FROM_REPOSITORY_NAME: bucketeer-io/bucketeer
          FROM_REPOSITORY_URL: https://github.com/bucketeer-io/bucketeer
        with:
          repo: ${{ env.DOC_REPO }}
          token: ${{ secrets.REPO_ACCESS_PAT }}
          workflow: update-changelog.yaml
          ref: main
          inputs: '{"doc_filename": "${{ env.DOC_FILENAME }}", "doc_filepath": "${{ env.DOC_FILEPATH }}", "doc_title": "${{ env.DOC_TITLE }}", "doc_slug": "${{ env.DOC_SLUG }}", "changelog_url": "${{ env.CHANGELOG_URL }}", "from_repository_name": "${{ env.FROM_REPOSITORY_NAME }}", "from_repository_url": "${{ env.FROM_REPOSITORY_URL }}", "commit_url": "${{ needs.setup.outputs.COMMIT_URL }}", "release_tag": "${{ needs.setup.outputs.RELEASE_TAG }}"}'
